title: English Now!
email: info@english-now.com
baseurl: "" # the subpath of the site, e.g. /blog
url: "http://english-now.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude: [ruby, Gemfile, Gemfile.lock, vendor]
